# Generated by Django 3.0.8 on 2020-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.TextField(blank=True, max_length=15, null=True)),
                ('organisation', models.TextField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
