# Generated by Django 3.0.8 on 2020-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200722_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactusquery',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
    ]
