# Generated by Django 3.0.8 on 2020-07-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_organisation_userextends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='State',
            new_name='state',
        ),
    ]
