# Generated by Django 3.0.8 on 2020-07-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_doc', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Organisation')),
            ],
        ),
    ]
