# Generated by Django 3.0.8 on 2020-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Invoices'),
        ),
    ]
