# Generated by Django 3.0.8 on 2020-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200730_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
