# Generated by Django 3.0.8 on 2020-07-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
