# Generated by Django 3.0.8 on 2020-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_qrcode_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
